server:
  port: 8080

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.cron-trigger.controllers
  writer-with-order-by-keys: true

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/sptribs/"
  application:
    name: sptribs Cron Trigger

idam:
  api:
    url: ${IDAM_API_URL:http://rse-idam-simulator:5000}
  s2s-auth:
    url: ${IDAM_S2S_AUTH:http://localhost:4502}
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM_S2S_AUTH_MICROSERVICE:sptribs}
  client:
    id: ${IDAM_OAUTH2_CLIENT_ID:sptribs}
    secret: ${IDAM_OAUTH2_CLIENT_SECRET}
    redirect_uri: ${IDAM_OAUTH2_REDIRECT_URL}
  systemupdate:
    username: ${IDAM_SYSTEM_UPDATE_USERNAME:st-test1@mailinator.com}
    password: ${IDAM_SYSTEM_UPDATE_PASSWORD:Pa55w0rd11}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}

azure:
  application-insights:
    instrumentation-key: ${app-insights-instrumentation-key:00000000-0000-0000-0000-000000000000}

trigger:
  date: ${TRIGGER_DATE:#{null}}
